idf_component_register(
  SRCS
  "main_ui.c"
  "main_event_handlers.c"
  "wifi_ui.c"
  "UI_commons.c"
  "./tile_uis/wifi_tile.c"
  "./tile_uis/ble_tile.c"
  "./tile_uis/other_tile.c"
  "./tile_uis/wifi_icons.c"
  "./tile_uis/bluetooth_icons.c"
  INCLUDE_DIRS
  .
  REQUIRES
  lvgl
  driver_init
  wifi_handler)
